### ISSUE TITLE
Project Submission Error: Unable to Submit Hackathon Project (v3.0.2)

### ISSUE THREAD

**Issue by manasa246** [rahul-bangar/Transfinitte_App#3]
**Issue Summary:**
Users are unable to submit their hackathon projects through the app (version 3.0.2).

**Steps to Reproduce:**
1. Launch the app (version 3.0.2).
2. Navigate to the "Project Submission" section.
3. Select a project to submit.
4. Follow the on-screen prompts to complete the submission process.

**Expected Behavior:**
Users should be able to successfully submit their hackathon projects, including project descriptions, team details, and code repositories.

**Actual Behavior:**
When attempting to submit a project, users encounter an error message: "Project Submission Failed. Please try again later."

**Additional Information:**
- App Version: 3.0.2 (latest from Google Play)
- Android Version: Android 10
- Device: Samsung Galaxy S10
- Reproducibility: The issue occurs consistently on Android 10 devices.

**Error Message:**
The exact error message displayed is: "Project Submission Failed. Please try again later."

**Notes:**
I've verified that the project details, team information, and code repository URLs are correct. There is no additional information in the error message or logs.

**Note to Developers:**
Please investigate and resolve this project submission issue promptly, as it is a critical feature for participants to complete their hackathon experience.

Thank you for your attention to this matter.

**Comment by rahul-bangar** [comment]
**Issue Resolved**

**Resolution Details:**
The root cause was identified to be related to data validation and it has been remedied, ensuring a stable and error-free experience during project submission.

**Next Steps:**
1. Please reattempt your project submission to confirm that the error is resolved on your end.
2. If you encounter any further issues or have additional feedback, do not hesitate to reach out.
